- name: Configurar servidor web
  hosts: all
  become: yes
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present
    - name: Iniciar Apache
      service:
        name: apache2
        state: started
    - name: Copiar archivo HTML
      copy:
        src: index.html
        dest: ./index.html
